### ISSUE TITLE
有计划上架AMO吗？；添加 license

### ISSUE THREAD

**Issue by yfdyh000** [harytfw/GlitterDrag#1]
1. 上架吸引更多使用者和开发资源。某些部分可能得调整。英文i18n尚未准备好。
2. 添加合适的许可证使其成为开源软件。

**Comment by harytfw** [comment]
对如何开源的步骤和协议不是很熟悉，不过这个扩展肯定是会开源的。
扩展已经提交到AMO，主要是什么时候可以审核通过。
英文翻译可能要以后有空闲时间再弄。

**Comment by yfdyh000** [comment]
可以参考 https://help.github.com/articles/licensing-a-repository/
本扩展结构不复杂，应该不难。但 nativeMessaging 的部分也许会被退回或建议修改。
没事，我也可以帮忙，但没有多少中译英的经验，以及有点担心代码冲突、注释是否要英文化。

我有尝试其他方案来复制图像，但也都不奏效。https://www.w3.org/TR/clipboard-apis/ 的 Writing to the clipboard 部分没有写支持位图。

**Comment by harytfw** [comment]
非常感谢你帮助这个扩展完成国际化 ：)
现在回复应该不算晚，扩展现在通过审核了，第一次完成一个比较完整作品并且通过让我感到有些兴奋和激动，未来我还会继续为这个扩展添加和完善功能。
最后还是要谢谢你的贡献。

**Comment by yfdyh000** [comment]
期待新版本更新到AMO，希望能吸引到一些国际用户和开发者。

等待 https://bugzilla.mozilla.org/show_bug.cgi?id=1356543

**Comment by yfdyh000** [comment]
AMO未更新。AMO页面的首页也需更新。

**Comment by harytfw** [comment]
我已经更新了页面介绍：https://addons.mozilla.org/en-US/firefox/addon/glitterdrag/
介绍了一下扩展的主要特性，不过配上的截图是新版本的，英语i18n也在新的版本才能见到。

吐槽一下，那个扩展审核好慢，这么多天排列位置基本没有变化。

**Comment by yfdyh000** [comment]
简体中文下的配图能改成中文版吧。

审核速度很难说，几小时到几个月都有过……大幅变更审核更慢些。
“标为实验性”还需要吗。扩展的“开发通道”是否已可用。
