### ISSUE TITLE
Eagerly waiting for English translation

### ISSUE THREAD

**Issue by ghost** [harytfw/GlitterDrag#10]
I need to replace the _Super Drag_ Firefox legacy add-on and _GlitterDrag_ would be a perfect Webextension replacement. Eagerly waiting for the English translation.

**Comment by harytfw** [comment]
I just update newest version **v1.41b2**. Maybe you can have a try. English translation is finished.

And I have added some feature in this version.

Before you start with this extension, I suggest you look at the option page and configure the actions.

You can found the xpi file that has been signed in releases page. Or click [here](https://github.com/harytfw/GlitterDrag/releases/tag/v1.41b2):

**Comment by zymase** [comment]
Just installed _GlitterDrag 1.41b2_. Far more complete than my previous _Super Drag_ legacy FF add-on. Fully translated (to English).

I'm currently setting the options. Personally I would have preferred that the search engine be that of the user's default search (as with _Super Drag_). I notice nevertheless  that it is possible to add another search engine than those included with _GlitterDrag_.  When clicking on Options/Search template/Add I see two boxes : I presume the first is for the new search enfine's name and the second for the template. Should be fine.

Many thanks for what appears after a first quick discovery a very nice and welcomed add-on.

**Comment by yfdyh000** [comment]
> Personally I would have preferred that the search engine be that of the user's default search (as with Super Drag).

This is need the https://bugzilla.mozilla.org/show_bug.cgi?id=1352598

**Comment by zymase** [comment]
> This is need the https://bugzilla.mozilla.org/show_bug.cgi?id=1352598
OK. That's the lot of Webextensions.

Anyway, adding my search engine was easy and works. All seems to work up to now.
_GlitterDrag_ has been really well thought and the options are presented in such a clear and logical way that settings are a breeze to adjust. Really very nice. And offers far more possibilities than _Super Drag_.
I think I'm happy and won't be the only one :)
