### ISSUE TITLE
抱歉问个很白的问题，这个拓展怎么用啊？

### ISSUE THREAD

**Issue by chenyue404** [harytfw/GlitterDrag#104]
设置了怎么保存呢？
启用了之后，网页上选字然后鼠标左键拖拽没有任何反应啊？

**Comment by harytfw** [comment]
首先，扩展不能在mozilla页面和浏览器内部界面（如扩展管理界面和新标签界面）生效。

设置一般是自动保存的。

启用扩展后，打开任意网页（除了上面提到的地方），拖拽 “选中的文字” 或 “链接” 到任意方向，然后扩展会根据你拖动的方向和配置执行不同的动作。

没有反应的话：
1.你可能需要重新启动浏览器
2.或选择“恢复默认”。如图 
![default](https://user-images.githubusercontent.com/14118053/46948750-af155600-d0b1-11e8-9489-2efd28cf8542.png)

**Comment by chenyue404** [comment]
谢谢解答，恢复默认一下就好了。
