### ISSUE TITLE
When dragging text with colon (":") browser opens error page "The address wasn’t understood"

### ISSUE THREAD

**Issue by h13Bishop** [harytfw/GlitterDrag#106]
If i drag for search something like this "asdasd: asdasd".
Any way to fix this? Thank you.

**Comment by harytfw** [comment]
the extension treats "asdasd: asdasd" as a link, so it directly open the link.
According to [wiki](https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#Generic_syntax) says,  "asdasd: asdasd" is a valid **URI**, but not a valid **URL**.

I will add a check to avoid this problem.

**Comment by h13Bishop** [comment]
Why close if it's not fixed?

**Comment by h13Bishop** [comment]
Confirm fixed. Thank you very much.
