### ISSUE TITLE
从外部程序拖拽文本进行搜索，会残留操作提示

### ISSUE THREAD

**Issue by licheedev** [harytfw/GlitterDrag#107]
如果开启操作提示，从外部程序，比如QQ拖文本进浏览器内容区域，原页面会残留操作提示，需要刷新页面才能把提示去掉。
![GIF](http://dimg.vim-cn.com/e9/cdc5a4ff934123af3146237f8746a70f4e62b1.gif)

**Comment by harytfw** [comment]
下个版本会修复
