### ISSUE TITLE
[feature request] Option to disable seemAsURL/fixupSchemer to copy verbatim text

### ISSUE THREAD

**Issue by danielmmmm** [harytfw/GlitterDrag#108]
I see how URL matching can be usefull for many. At the same time, I find it usefull to be able to copy verbatim text.

E.g. copying "xyz.com" should remain as "xyz.com" in the clipboard, instead of being changed to "http://xyz.com"

**Comment by harytfw** [comment]
Maybe somebody would need it.

**Comment by danielmmmm** [comment]
I agree that some (many?) need the "http://".
That is why there could be an option to switch it off for the other people like me :-)

**Comment by danielmmmm** [comment]
[63056b6](/harytfw/GlitterDrag/commit/63056b64775a354ddf829191338570edcdc53c23) is looking good!
Thanks a lot :-)
