### ISSUE TITLE
功能需求

### ISSUE THREAD

**Issue by byzod** [harytfw/GlitterDrag#11]
不清楚WebExt能做到哪些，总之先列在这里( ´･ω･`)

1. 超时取消
  拖拽启动后，用户鼠标悬停且未放开左键xxx毫秒后，取消拖拽操作

2. Textarea例外
  在Textarea等编辑区域内不触发拖拽，否则无法用拖拽进行正常文本编辑

3. 识别用户搜索引擎
  目前选择搜索的引擎时，只有`默认`一个选项，希望能够识别用户已有的引擎并可以作为拖拽搜索引擎使用

4. 识别图片链接（即在legacy代码中，当拖拽事件的dataTransfer既包含`application/x-moz-file-promise-url`又包含`text/x-moz-url`时）
  在图片部分的选项设置中，允许用户对图片链接进行操作设置
  例如 `图片-右：打开-图片链接`
  这样，用户就可以区别设置对“图片文件链接”和“图片链接”的操作
  例如本issue中，我的头像图片，右键菜单中`复制地址`和`复制图片地址`是两个不同的操作

5. 链接另存为
  或称“下载”，效果等同/类似于在链接上右键另存为

6. 在当前tab打开链接/图片链接/图片文件链接

7. 直接保存图片到指定目录

8. 在当前页面使用浏览器搜索（ctrl+F那个）并高亮选中文字

9. 站内搜索文字&搜索相似图片
  实际上就是内置一些额外搜索参数
  站内搜索即调用baidu或google的`site:domain.com`功能，摘抄紫云飞的DragToGo相关代码如下（legacy）
  ```javascript
  var searchStrInSite = "site:" + getTopWin().getBrowser().currentURI.host + " " + dragStr/*拖拽的文字*/;
  var Ss = Components.classes["@mozilla.org/browser/search-service;1"]
          .getService(Components.interfaces.nsIBrowserSearchService);
  var engine = Ss.currentEngine;
  //站内前台搜索文字
  gBrowser.loadOneTab(
      engine.getSubmission(searchStrInSite, null).uri.spec,
      {
          referrerURI: aReferrerURI, 
          inBackground: false
      }
  );
  ```
  搜索相似图片即把图片地址喂给搜索引擎
  摘抄DragToGo相关的代码
  ```javascript
  //前台搜索相似图片(Google)
  gBrowser.loadOneTab(
      "https://www.google.com/searchbyimage?image_url=" 
          + encodeURIComponent(event.dataTransfer.getData("application/x-moz-file-promise-url")),
      {
          referrerURI: aReferrerURI, 
          inBackground: false
      }
  );
  ```

10. 识别链接文字
  例如作为文字拖拽`pan.baidu.com/s/xxxxx`时，视作链接进行处理
  还是摘抄DragToGo相关的代码
```javascript
// URL guess
this.SeemAsURL = function (url) {
    // url test
    var DomainName = /(\w+(\-+\w+)*\.)+\w{2,7}/;
    var HasSpace = /\S\s+\S/;
    var KnowNameOrSlash = /^(www|bbs|forum|blog)|\//;
    var KnowTopDomain1 = /\.(com|net|org|gov|edu|info|mobi|mil|asia)$/;
    var KnowTopDomain2 = /\.(de|uk|eu|nl|it|cn|be|us|br|jp|ch|fr|at|se|es|cz|pt|ca|ru|hk|tw|pl|me|tv|cc)$/;
    var IsIpAddress = /^([1-2]?\d?\d\.){3}[1-2]?\d?\d/;
    var seemAsURL = !HasSpace.test(url) 
                    && DomainName.test(url) 
                    && (KnowNameOrSlash.test(url) 
                        || KnowTopDomain1.test(url) 
                        || KnowTopDomain2.test(url) 
                        || IsIpAddress.test(url)
                        );
    return seemAsURL;
}
```

11. 外部链接（有待进一步讨论）
  从浏览器外部拖动进入浏览器内部的对象处理（例如从QQ里拖过来的一张图，或者Steam拖过来的一段文字）

**Comment by yfdyh000** [comment]
3. 需要 https://bugzilla.mozilla.org/show_bug.cgi?id=1352598 ，有希望
8. 可能需要 https://bugzilla.mozilla.org/show_bug.cgi?id=1332144
11. 或许超出本扩展范畴？

其他应该有可能。

功能设计还可参考手势扩展Smartup、[Gesturefy](https://www.firefox.net.cn/read-54305-1)，以及[Drag & DropZones](https://addons.mozilla.org/firefox/addon/drag-dropzones-revived/)等。

**Comment by byzod** [comment]
@yfdyh000 现在扩展已经有拖拽“下载图片”的功能了，个人觉得对于链接也应该有同等操作
下载本身还有读取文件名之类一系列乱七八糟的后续处理，不知道扩展能不能只做到调用原生“另存为”的功能，让浏览器完成后面的操作
如果能实现就太好了，其一DTG作为uc.js脚本，webext替代短期是没希望的，其二由于DTG脚本本身适配的问题，对于其他涉及到拖拽事件的扩展还有冲突，能有webext扩展替代是最好的

**Comment by yfdyh000** [comment]
我写错了，5. 的回复是给 11.（从浏览器外部拖动进入浏览器内部）的。处理外源的拖动是否是本扩展的目标，会增加多少成本，能否检测出网页在接受拖动。

**Comment by byzod** [comment]
@yfdyh000 在legacy扩展里这个检测倒是挺容易的，总而言之先写上去了，如果不能实现也问题不大，毕竟应用场景不是很多，也因此放在了最后一条

**Comment by harytfw** [comment]
非常谢谢 @byzod 提出的建议和和一些说明。
对于一些需求 3,8,11  @yfdyh000 也解释了，只要webext提供相应的api，还是可以实现的。

7. 指定目录只能放在浏览器默认的下载目录里面（不确定）
9. 现在扩展已经有自定义搜索引擎的功能，也支持%s作为关键词。我认为有两种实现方法：可以增加一个替换字符串如%a，扩展把 %a 替换成 当前域名，也就可以实现站内搜索；直接给出选项自己选择。
11.  其实在之前的版本的时候，就已经考虑过处理浏览器外部拖动的对象，不过让扩展处理可能对页面自己的拖拽产生冲突（比如github里的拖拽上传文件功能）。也可能实现更多的功能而不产生冲突（完美状态），这或许要看以后的具体效果。

其他的实现我会尽力实现和完善。

**Comment by yfdyh000** [comment]
7：只能放在下载目录里，但可以建立子文件夹，参考 https://github.com/danny0838/webscrapbook

**Comment by gsy111** [comment]
从窗口外拖进来的文字进行搜索,最好有这个功能.

**Comment by fireattack** [comment]
现在每次修改search template都要手动刷新才会在action的选项里出现……

**Comment by harytfw** [comment]
已经完成一部分了。
关于外部拖拽，dataTransfer在webext下有bug，无法调试，所以就还没去写这部分的内容

**Comment by harytfw** [comment]
现在剩下最后一个：识别用户搜索引擎

**Comment by hdd60311** [comment]
路過提醒一下[bug1352598](https://bugzilla.mozilla.org/show_bug.cgi?id=1352598)官方已經添加支持了

**Comment by egops** [comment]
需要一个制定排除页面的功能, 有些页面会需要拖拽的功能, 比如看图之类的. 使用页面原本的拖拽功能.

**Comment by harytfw** [comment]
全部完成
