### ISSUE TITLE
無法複製連結文字或網址

### ISSUE THREAD

**Issue by GJRobert** [harytfw/GlitterDrag#110]
你好，我在最新（56.2.7.1）的 Waterfox 上使用這個 addon，拖曳後開啟連結的功能正常，但是設定在 link 上往左下拖曳 = 複製文字、往右下拖曳 = 複製連結的動作，都沒有用。似乎所有複製的動作，我都無法成功。不知道是不是有什麼瀏覽器權限需要開啟？或是我什麼地方設定錯誤了？

**Comment by harytfw** [comment]
应该是兼容性问题
虽然在 Waterfox 上可以使用部分功能，但我不推荐在 Waterfox 上使用我这个addon。
1. 这个addon是使用了一些 firefox v56 之后的API，所以在旧版本上可能会出问题。
2. Waterfox 目前同时支持 xul addon 和 webextension，但会使用 Waterfox 的人一般是希望继续使用旧式 xul addon，因此在兼容性上我就基本不会考虑 firefox 衍生品（使用人数少）。

Waterfox  的话推荐使用 [Easy DragToGo+](https://www.firefox.net.cn/read-29894)，从最后往前翻页应该可以找到可用的 addon。

**Comment by GJRobert** [comment]
謝謝你，沒關係，那麼，我會繼續使用 Glitter Drag，因為我原本是使用 DragIt 的（更之前很多年，我一路使用 Super Drag and Go、Drag de Go、Easy DragToGo，最後用到的是功能最多也最複雜的 DragIt……），但 DragIt 被 e10s 毀了，而我發現，還好你的 Glitter Drag 功能也是很多而且很好用，而且體驗上甚至比 DragIt 更好。

複製網址或文字的部分，我應該可以用 [Link Text and Location Copier](https://evilnickname.github.io/link-text-location-copier/) 代替，雖然不像 drag 類套件那麼快，但也行。（蠻推薦的）
