### ISSUE TITLE
无法打开设置界面--找到了，是不会用

### ISSUE THREAD

**Issue by sstiger1230** [harytfw/GlitterDrag#117]
安装了Firefox 69.0.3 x64版本，操作系统 Windows 10 1903 x64，安装了扩展后，点击图标没有出现设置界面，而是一个链接“ Add this site to the exclusion list”。

![Annotation 2019-10-12 173738](https://user-images.githubusercontent.com/15171715/66699181-01b23e00-ed17-11e9-8356-24491f50e35c.png)

**Comment by sstiger1230** [comment]
Glitter Drag 版本是 1.56.7

**Comment by sstiger1230** [comment]
太不好意思，找到了设置界面。

**Comment by Amatuki** [comment]
设置界面在哪里？现在找不到了....
