### ISSUE TITLE
Don't work in firefox 68.3.0esr (64-bit)

### ISSUE THREAD

**Issue by sylar-Jeon** [harytfw/GlitterDrag#119]
I really appreatiate with this extension.

But, don't work in firefox 68.3.0esr (64-bit) in window OS.

GlitterDrag version 1.56.7

Please fix it.

**Comment by sylar-Jeon** [comment]
I fix it. 
The problem is restore setting in new firefox profile. 

I set 'resotre to default' and recreate all setting again.
Now it works. 

I'm sorry to make this noise. 

Thank you. BR

**Comment by jhdxr** [comment]
I run into the same issue on firefox 75 (win 10 x64)

I tried a fresh profile with only this extension enabled, but still no luck.

**Comment by jhdxr** [comment]
my bad. it actually works. (I used to use panel only, which is not the default behavior)
now I have to figure out what went wrong on my daily profile, maybe conflict with some other extension. will update this issue once I find any clue.
