### ISSUE TITLE
Improvement: adding the destination to action tips

### ISSUE THREAD

**Issue by ghost** [harytfw/GlitterDrag#12]
Enjoying _GlitterDrag 1.41b2_ on Firefox ESR 52.3.0 (x64).

No issue, only a suggestion for improving the _Options / General / Show actions tip_ feature which shows only the action type but not the action type's destination. For instance it will show _Search_ but not include what search I have opted for. Say, dragging test, left for **Search** with DuckDuckGo and right with Qwant ... in both cases, dragging a text left or right the tip will show Search when it would be an improvement, IMO and if feasible, to add **Search with** [DuckDuckGo, Qwant here].

It's only a wish. Thanks!

**Comment by harytfw** [comment]
A good suggestion. 
I would like make this feature more flexible. Such as providing a pattern setting and the  **actions tip** 's content depends on this pattern.
for example, assuming the pattern is   _**%a %w in %e**_  ,  the tip's content becomes  _**Search (Keyword) in (Engines'name)**_  

**%a** represents action's name, **%w** is keyword you opt, **%e** is engine's name

I will put this on plan.
