### ISSUE TITLE
在火狐94.0.2版本下，拖拽搜索不起作用，能打开窗口，但是无搜索结果。

### ISSUE THREAD

**Issue by totodata** [harytfw/GlitterDrag#139]
在火狐94.0.2版本下，拖拽搜索不起作用，能打开窗口，但是无搜索结果。地址栏空白。

**Comment by totodata** [comment]
经过研究，应该是和系统的附加组件管理器里面的选项启用拖拽手势冲突了。我安装附加组件管理器后，在选项里面，取消开启，即可。

**Comment by tuyouta** [comment]
我没有安装附加组件管理器，也是拖拽成空白页，希望作者能维护下！

**Comment by a8778700** [comment]
我也没有附加组建管理器

**Comment by stanz2g** [comment]
同样现象。用另一个扩展Hyper Drag可以正常拖拽搜索，但其他方面不如本扩展。望修复

**Comment by stanz2g** [comment]
> 同样现象。用另一个扩展Hyper Drag可以正常拖拽搜索，但其他方面不如本扩展。望修复

FF95版本中拖拽搜索，如果是后台打开工作正常，前台打开都是空白页

**Comment by totodata** [comment]
发现不是标签管理的问题，现在也是经常空白了。

**Comment by totodata** [comment]
暂时用这个替代了。
https://addons.mozilla.org/zh-CN/firefox/addon/smartup/

**Comment by wzcasd** [comment]
http://mozilla.com.cn/thread-343905-1-1.html 安装这个再取消勾选就行了

**Comment by R8s6** [comment]
暫時解決辦法:

1. 在 "Actions" 標籤下, 對於 Text, 將 Search 改成 Open
2. 第二行是 current:default (Firefox 的搜索引擎我默認是 StartPage)
3. background/foreground 貌似不影響

如果沒有用, 我之前是將 glitter 卸載, 關閉 firefox, 再安裝 glitter drag 過, 您也可以試試.

**Comment by tuyouta** [comment]
把火狐默认启用的网站进程隔离关掉就没问题，fission.autostart设置为false

**Comment by totodata** [comment]
经过测试，以上都没有效果。作者不更新了。

**Comment by totodata** [comment]
经过测试，改用这个英文版，可以正常使用

https://addons.mozilla.org/zh-CN/firefox/addon/glitter-drag-plus/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search

**Comment by R8s6** [comment]
Hi,

glitter-drag-plus 的插件頁面引用的源代碼依然是上游項目 GlitterDrag (最後一次 commit 在 2020), 所以還請作者 ililu 有空時更新一下 glitter-drag-plus 自己的源代碼網頁.

非常感謝.

Sent with [ProtonMail](https://protonmail.com/) secure email.

------- Original Message -------

**Comment by harytfw** [comment]
不好意思, 因为疫情和工作的问题, 耽误了更新.

我在 github 上找不到 ililu, 所以我手动对比了一下  ililu 的修改, 主要是在打开标签页的时候增加了一个短暂的延时.

```js
await new Promise(r => setTimeout(r, 50));
```

估计有时候标签页会处于不可用状态

**Comment by harytfw** [comment]
v1.56.9 修复了这个问题
