### ISSUE TITLE
firefox101下无法保存设置

### ISSUE THREAD

**Issue by turbidsoul** [harytfw/GlitterDrag#142]
![图片](https://user-images.githubusercontent.com/554941/171309635-924fbb24-8459-484d-a470-9fb01993781f.png)
以前的设置也没有了。

![图片](https://user-images.githubusercontent.com/554941/171309675-086a9686-095e-4f5d-af51-77e476b33f62.png)
控制台上能看到初始化失败了。

使用中扩展没有生效

**Comment by turbidsoul** [comment]
@harytfw 3Q 能读取之前的配置成功初始化，并且之前的错误没有在出现

**Comment by lonix1** [comment]
Thanks for making and maintaining this addon!
