### ISSUE TITLE
项目状态和新版本

### ISSUE THREAD

**Issue by harytfw** [harytfw/GlitterDrag#147]
只是出于兴趣原因，我创建了这个扩展。在项目初期，也得到了许多人的帮助和反馈，在这里非常感谢。

但是因为在扩展设计上的问题，既要保持向后兼容又要添加新特性非常困难。我更愿意让 v1 版本停留在维护状态，然后重构和重新设计新版本的闪耀拖拽。

跟 v1 相比，新版本的扩展主要有：
- 同时支持 Firefox 跟 Chromium
- 使用 Manifest v3
- 新的配置方案 （但是不跟 v1 兼容）
- 多种操作方式：四方向，链式方向 （类似手势扩展，多个方向组合然后执行命令），环形菜单，方格菜单 (替换 v1 的面板功能)
- 删除一些不好用的特性或功能：翻译功能，根据图片搜索，内置的搜索引擎列表，还有其他小功能

有一些问题希望可以给一些建议或者反馈：
- 扩展的名称目前暂定是 英文 "Glitter Drag Pro" / 中文 "闪耀拖拽 Pro"，是否有其他更好的名称？
- 新的扩展跟之前的扩展基本上不兼容，相当于全新设计，是否要放在当前的仓库里，还是新建仓库 (我个人更倾向新建仓库)
- 你觉得有什么特性/功能想要添加到新版本中？还是其他完善之处

**Comment by ililu2000** [comment]
1.提个建议，当前这个设置界面太寒碜了，可以参考[Gesturefy](https://addons.mozilla.org/zh-CN/firefox/addon/gesturefy)这个扩展的设置界面，简单大方。
2.扩展的名字有点难记，可能是我英文不太好，希望简单点 Drago?

**Comment by harytfw** [comment]
https://github.com/harytfw/GlitterDrag/releases/tag/v2.1.0

新版本终于发布了，虽然鸽了很久了。

个人感觉配置界面简单好用无问题就行，不过新版本也做了一些调整。

**Comment by harytfw** [comment]
会考虑换新名字的，或许 Dragon / Dragofly 会更好一些 ？

**Comment by harytfw** [comment]
新扩展名称为 GlitterDrag Pro，同时为了避免影响旧版本的用户，新版本扩展会另外上架 AMO
