### ISSUE TITLE
Open sequence "feature" request.

### ISSUE THREAD

**Issue by regtoaccess** [harytfw/GlitterDrag#155]
I am a long time user of this extension, and the one thing I always found lacking was the option to let firefox handle the tab open sequence (basically for this extension to emulate ctrl + left click).

I searched the issues section and found an identical request: #105

Since that "issue" has been closed without implementation, I assume you have a reason for it. If so, go ahead and close this one as well (since is pretty much identical). Though I hope this can be implemented in the upcoming GlitterDrag Pro.

**Comment by harytfw** [comment]
It seems that the behavior of the tab sequence is obscure, see: [<https://bugzilla.mozilla.org/show_bug.cgi?id=1485683>](https://bugzilla.mozilla.org/show_bug.cgi?id=1485683), not only the tab API exposed by the browser will affect this, but also the config of Firefox will do. Maybe a different OS will affect this too?

For my use case, the order is not significant, but it would be great to provide a good experience for the user.

From the self-test, If I only specify the owner tab, without tab index, the behavior is identical with ctrl + left click

**Comment by regtoaccess** [comment]
Don't know what you refer to by "_**only specify the owner tab, without tab index**_" (maybe a setting that's present on linux firefox?), but flipping "**browser.tabs.insertAfterCurrent**" in about:config doesn't change the behavior explained in #105.

For now, I will stick with the older version along 'select after closing current' to mimic the ctrl+left click behavior and assess my options when it will stop working.

Thanks.
