### ISSUE TITLE
点击插件是“将此站点添加到排除列表”，而不是设置面板！

### ISSUE THREAD

**Issue by Cloudyz** [harytfw/GlitterDrag#163]
点击插件是“将此站点添加到排除列表”，而不是设置面板！作者操作说明从第0步就没办法实现。最后还是我在xpi文件里发现有options.html，然后这网页就能改配置了。

**Comment by harytfw** [comment]
v1 老版本暂时不维护了，没有什么重大BUG，影响使用暂时就不动了。
