### ISSUE TITLE
Glitter Drag 每次启动都是google引擎 

### ISSUE THREAD

**Issue by aglent** [harytfw/GlitterDrag#18]
刚用这个扩展 发现一个问题 
我设置好搜索引擎是bing 但是每次重启FF55后 划词搜索引擎变回默认的google了 要重新进入扩展的配置页面后才会变正常

**Comment by harytfw** [comment]
我这里已经重现你的问题。
你搜索引擎列表里面是不是只有一个bing？如果是的话将来的版本会修复这个问题。临时解决方法，添加多几个搜索引擎，然后在手动选中bing。

如果不是的话，那我还需要找一找原因

**Comment by aglent** [comment]
安装扩展后 列表里有很多引擎 bing是第二个
我的操作是这样的：选择search template 列表里选择bing  下面出现bing搜索串 点击右边的钩 然后关闭配置页面 这时可以正常用bing划词搜索了 但是重启FF后变回google搜索
后来我又进入search template页面 重新列表里选择bing 下面会出现重复的bing搜索串 删除多余的一个 点钩 关闭配制页面 这回接完全正常了 重启FF也不会变回默认的google搜索了
你看看问题出在哪里

**Comment by harytfw** [comment]
我指的搜索引擎列表是指  ```动作/文本/方向/搜索引擎列表```（下面有一张图片）

![default](https://user-images.githubusercontent.com/14118053/29714373-7cba4716-89d5-11e7-9d6e-7902205e498f.jpg)

其实是这样的：因为众口难调，加之搜索引擎众多，每个人对搜索引擎的使用习惯不同，所以我把他们单独拿出来放在一个页面里面，可以根据自己的需求添加或修改。

在“search template” 页面修改引擎只是修改我上面所指的那个列表，扩展并不知道你具体要使用那个引擎，也不会自动修改每个方向调用的引擎。

虽然每个动作都可以分配一个引擎，但因为设计没有考虑周到问题，只有一个引擎选项的情况下是无法保存的（只有选项更改的情况下才会保存）。

下面重新说一下临时解决方法（不知道你使用的是英文版扩展还是中文版，以英文为例吧）：

- 在“search template” 页中添加你想要的引擎
- 在“Actions” 页中为具体的类型以及方向分配搜索引擎，如 **Text**-**Up**,  第一个选项是“执行动作“，我建议你选择 “Open”。接下来选项都有悬停说明，只要把鼠标悬放在上面就会显示。最后一个选项就是要调用的引擎。
- 我说过只有一个搜索引擎选项是无法保存的，所以你要有两个以上的引擎选项，选中“Bing Search”（理论上你只要修改一个方向，其他的都会保存。）

**Comment by aglent** [comment]
谢谢指点 现在明白了
