### ISSUE TITLE
繁体翻译

### ISSUE THREAD

**Issue by zhtw2013** [harytfw/GlitterDrag#19]
你好，我是台湾人，卡饭上看到你的扩展

Github源码里的语言文件应该是最新的吧？我已经翻好繁体了。
翻译文件见附件，望加入。

[zh-TW.zip](https://github.com/harytfw/GlitterDrag/files/1253673/zh-TW.zip)

**Comment by yfdyh000** [comment]
感谢，已加入。
https://github.com/harytfw/GlitterDrag/blob/dev/_locales/en/messages.json 是开发中的最新版，已有一些字符串变更。

**Comment by zhtw2013** [comment]
明天弄好给你。

**Comment by zhtw2013** [comment]
开发版我用简体版文本来改繁体应该没问题吧....我简体到繁体的字典已经做好了欸 哈哈
话说可以寄email把你的QQ号传给我吗？ 直接用QQ联系比较方便。
zhtw2013{at}gmail.com

**Comment by zhtw2013** [comment]
Dev已完成  基于Dev简体文本做的。(9 hours ago上传的那个版本)

[DEV zh_TW.zip](https://github.com/harytfw/GlitterDrag/files/1254346/DEV.zh_TW.zip)

**Comment by yfdyh000** [comment]
质量没问题就行。卡饭私信已回，不用QQ，建议用Edit功能发PR。
SettingDownloadDirectoryHelperText 的格式已过时。暂时不更新也行，看作者未来开发，dev可能频繁变动。
或许该弄一个翻译平台，不知是否必要。https://www.transifex.com/ https://crowdin.com/ https://hosted.weblate.org 等可选。

**Comment by harytfw** [comment]
弄一个翻译平台确实方便许多，而且这些翻译平台都对开源项目免费。
不过我对这些平台并不是太熟悉，也不知道要选哪个。以第一印象来看，crowdin.com/ 比较好

**Comment by zhtw2013** [comment]
閃耀拖曳
------------------------------------------
一個拖曳附加元件，支援拖曳文字、鏈結和圖像，同時開啟、複製或搜尋這些東西。

------------------------------------------
附加元件的主要特性：
支援四個方向（上下左右）
允許拖曳類型：文字、鏈結、檔案
支援的功能：開啟、複製、搜尋
功能支援的類型：文字、鏈結（圖像暫時還不支援）
選擇標籤頁開啟的位置：分頁之頁首，分頁之頁尾，目前分頁的右邊
指定如何開啟新的分頁：前景、背景
這些特性都是可以組合的，也就是說你可以這樣做：

向上拖曳一個鏈結並在背景末尾的位置開啟它；
向右拖曳一個鏈結用來複製鏈結的文字

詳細的設定請檢視附加元件的選項


原始程式碼：https://github.com/harytfw/GlitterDrag
如果你有任何問題或建議請在下方發表你的評論，或在github上提出。

**Comment by harytfw** [comment]
AMO上的介绍已经更新，谢谢你提供的繁体翻译。

**Comment by zhtw2013** [comment]
啊啊啊啊 有段没改到

「選擇標籤頁開啟的位置：分頁之頁首，分頁之頁尾，目前分頁的右邊」
请改为
「選擇分頁開啟的位置：分頁之頁首，分頁之頁尾，目前分頁的右邊」
