### ISSUE TITLE
从QQ拖拽进来的文字无法搜索

### ISSUE THREAD

**Issue by gsy111** [harytfw/GlitterDrag#20]
显示If you see it, please report to the author of GlitterDrag
ff55.0.3 版本

**Comment by gsy111** [comment]
从QQ拖拽进来的图片在搜索图片的重定向页面停留时间很短,没时间选择百度还是Google

**Comment by gsy111** [comment]
网页里的图片要以图搜图要怎么设置?
我这样设置无效
[img]https://i.loli.net/2017/09/06/59af954f5d69d.jpg[/img]

**Comment by harytfw** [comment]
我现在在用ff57, 后面我会用55测试.
现在以图搜图功能只是测试阶段, 还不能选择百度还是Google. 将来会完善
那个重定向页面在原本设计上就不是选择图片搜索引擎的地方,  不过你也可以直接打开这个页面, 链接是 moz-extension://ca8e81c3-d8d0-4926-9125-ec9591ded216/redirect/redirect.html#

**Comment by gsy111** [comment]
明白了,作者辛苦了

**Comment by harytfw** [comment]
最新版本应该修复了这个bug
