### ISSUE TITLE
从任何的文字输入框/搜索框进行拖动搜索都无效

### ISSUE THREAD

**Issue by gapplef** [harytfw/GlitterDrag#22]
Firefox 55 @ Ubuntu Gnome 17.04
使用场景：用百度搜索了某个关键词，对结果不满意，想再用Google搜一下却无法拖动；
之后发现只要是文字输入框就无法拖动搜索。
之前使用的Easy DragToGo+，无此问题。

**Comment by harytfw** [comment]
因为#11 第2项中有提到希望在textarea 等编辑区不触发拖拽，所以我排除了 input、textarea 这些文字输入区的拖拽。
我在后面的版本会提供选项，让用户自行选择是否在文字输入框触发拖动

**Comment by gapplef** [comment]
设置选项感觉少点更好。能不能做到拖出文字输入框才触发搜索，不拖出文字输入框就不搜索，这样应该可以同时满足两个需求。

**Comment by harytfw** [comment]
你现在可以试试最新的版本： https://addons.mozilla.org/zh-CN/firefox/addon/glitterdrag/versions/beta

**Comment by gapplef** [comment]
新版本问题得到解决，顺滑如丝，非常感谢！
一个小问题：设置的时候有的时候可以立即生效，有的时候又必须重启才能生效，很烦。

**Comment by harytfw** [comment]
关于那个小问题，根据你所说应该是间歇出现，那么我这里就比较难重现问题。可以的话重新开一个issue，我方便追踪和修复。

**Comment by harytfw** [comment]
我可以重现问题
应该是在改代码的时候忽略了输入框的例子。
下午或晚上更新吧
