### ISSUE TITLE
带链接图片的处理方式

### ISSUE THREAD

**Issue by thelastfantasy** [harytfw/GlitterDrag#26]
是按链接处理还是按图片处理，我个人习惯所有图片上往左拖动时都弹出另存为窗口，
这里应该提供一个选项比较好。

还有很多时候带链接图片的链接的href就是图片src本身，这时候是不是也应该做一下特殊处理。

还有个问题，pageexpand扩展弹出的图片好像没法拖动，这好像是因为GlitterDrag直接对元素使用了事件绑定而非事件委托所以造成了页面新添加元素无法拖动？

**Comment by harytfw** [comment]
如果想另存图片的话，**链接**里有“图像地址优先”的选项。还可以启用ctrl键和shift键的动作。
因为现在的选项页的代码比较乱，不好单独实现你的要求。

特殊处理是指把这种情况当成图片处理吗？

我是直接对document监听事件，根据捕获阶段和冒泡阶段传递的规则，只要不使用event.stopPropagation()，都会在document触发。 对可能影响页面本身的拖动（拖拽）情况也做了一些判断，尽量减少对页面的影响。我需要测试才能找到原因

**Comment by fireattack** [comment]
另存带链接的图像按照2L说的搞定了，但是如何实现可以对带链接的图片进行反向搜图？

**Comment by harytfw** [comment]
@fireattack 
https://github.com/harytfw/GlitterDrag/wiki/%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8%E6%90%9C%E7%B4%A2%E5%BC%95%E6%93%8E
看看有没有帮助

**Comment by fireattack** [comment]
谢谢，不过我是指“以上传图像文件的方式搜索”这种。

**Comment by byzod** [comment]
不需要处理啊，只需要增加提供给用户选择就可以了

例如
图片 向上拖拽的操作，`打开` 操作可选 `图片地址` 或 `图片上的链接`
当图片没有带链接的时候，向上拖拽无操作，或者打开图片地址

**Comment by fireattack** [comment]
现在已经有选项了吧，只不过做在了链接那边而已

（除了上面提到的以图片搜图有问题以外）

**Comment by harytfw** [comment]
"总是把含图片的链接当成图片类型"，应该实现了你需要的功能。
