### ISSUE TITLE
Broken after latest update

### ISSUE THREAD

**Issue by Qwash** [harytfw/GlitterDrag#29]
The addon broken after latest update on AMO
I traced the problem to this switch "privacy.resistFingerprinting"
it can't work anymore with this switch "True"
I checked with a new profile that doesn't have any setting in the prefs.js but this
user_pref("privacy.resistFingerprinting", true);

Then I installed the addon from github using about:debugging and tried all versions to see which update make it broken
it works well until version "v1.50.0b10"
from "v1.50.0" and on AMO "v1.51.3" it's broken
I reverted back to 1.41 for now

Win7 x64, FF55.0.3 (x64)

**Comment by harytfw** [comment]
I hava no idea why it is broken after changing "privacy.resistFingerprinting" to true
It seems that "privacy.resistFingerprinting" has some bug now
I will do more search and test on it.

**Comment by harytfw** [comment]
I can not find a way to solve this problem.
But I think you should try install the latest version in FF56.

**Comment by Qwash** [comment]
I'm using latest firefox stable version now (56.0 <x64>)
it still doesn't work
manythings disabled and spoofed when privacy.resistFingerprinting = true
something changed since v1.50.0b10 caused this problem
I'm still using 1.41 and it is working fine

**Comment by harytfw** [comment]
Maybe it was introduced since 470233e
If 1.41.1b0 works well, I can confirm the source causing bug.
Install 1.41.1b0 hrer: https://addons.mozilla.org/zh-CN/firefox/addon/glitterdrag/versions/beta

**Comment by harytfw** [comment]
althought I encounter a bug when privacy.resistFingerprinting = true, I don't know whether it is the same problem.
maybe I forget to ask you what the broken detail.
* when dragging things, can you see the mouse cursor becomes prohibition sign(like ∅ ) ?
* can you upload the configuration file?
Thank you for all your assistance, I won't give up fixing this bug.

**Comment by Qwash** [comment]
No, dragging things appear as normal
When you release the mouse all directions treated as "UP" direction
Texts as example
Create any 3 search templates
Set in texts settings
Direction Control : normal 4 directions
Up,Down,Left "Search" and set for every direction a different search engine
Right, External "No Action"
Drag&drop any text all will be searched with the search engine you put in "UP" direction in the settings

**Comment by harytfw** [comment]
Please try [v1.52.2](https://addons.mozilla.org/zh-CN/firefox/addon/glitterdrag/).

**Comment by Qwash** [comment]
Fixed 💯 
Thank you!
