### ISSUE TITLE
选项UI建议：增加说明，且只在有效时出现

### ISSUE THREAD

**Issue by fireattack** [harytfw/GlitterDrag#30]
增加说明的意思是对每一列加个header，否则不清楚是啥。

“只在有效的时出现”现在部分选项似乎已经有（例如，选成“donwload”的话后面的选项会变），但是还有待改善——例如，选成“Open”时最后的搜索引擎选项不该出现。

最后外一则：外部/Outer写成“从外部”以及 From external 之类的是不是好点。现在给人的感觉是拖拽到外部……（尤其是和Up/Down啥的并列）。

**Comment by harytfw** [comment]
选项的设计确实不好，有机会的话我想重写选项页面。

对**文字**来说，“OPEN” 可能是打开链接，也可能是搜索。我认为只需对**链接**和**图像**隐藏搜索引擎选项，对**文字**继续显示这个选项。

“从外部" 和  "From external"  相比现在的用词更贴切，我会在新版本中更新这两个翻译
