### ISSUE TITLE
“在关闭所有子标签页后，切换到父标签页. (会覆盖上面的选项) ”选项的副作用

### ISSUE THREAD

**Issue by fireattack** [harytfw/GlitterDrag#32]
重现步骤

1. 设置如下：

![image](https://user-images.githubusercontent.com/4130991/30892038-0b45e898-a2fc-11e7-88ca-505b2b16202c.png)

![image](https://user-images.githubusercontent.com/4130991/30892039-0f485692-a2fc-11e7-9ca5-81c2e7b6dcbd.png)

(其他设置无所谓）

打开两个网站，操作左侧的A。
拖拽打开2个链接，会在后台标签页打开A1、A2。切换至A1然后关闭，正确切换到A2；再关闭A2，可以正确回到父标签页A。

**之后**，用**中键点击**打开两个链接，会在后台打开A1和A2。切换至A1并且关闭

正确结果：切换至A2
错误结果：切换至A

**Comment by harytfw** [comment]
“在关闭所有子标签页后，切换到父标签页”只对通过拖拽打开的标签页有效，对使用**鼠标中键**打开的标签页没有效果。

虽然本扩展完全可以实现类似特性，但我认为这个特性应该属于标签页管理型的扩展

因此，我把这些功能都设计成选项，避免与标签页管理扩展的功能产生重突

**Comment by fireattack** [comment]
@harytfw 你没理解我的意思。

现在问题就是对使用鼠标中键打开的标签页**有了效果**。

如果你不进行“拖拽打开2个链接，会在后台标签页打开A1、A2。切换至A1然后关闭，正确切换到A2；再关闭A2，可以正确回到父标签页A。“这步操作，鼠标中键打开的标签页切换是正常的——关闭A1会切换到A2，这也是Firefox的默认效果（即：如果完全不安装GlitterDrag的效果）。

但是现在会导致不正常：关闭A1没切换到A2，反而切换回了A。这个不正常的效果**只在你进行过拖拽操作之后才会出现，否则不会**

**Comment by harytfw** [comment]
对不起，之前没有彻底理解你的意思。
我在新的版本修复了这个问题，顺便修复 #31 
https://addons.mozilla.org/zh-CN/firefox/addon/glitterdrag/versions/beta

**Comment by fireattack** [comment]
经过测试有效，感谢！
