### ISSUE TITLE
有时不能下载图片

### ISSUE THREAD

**Issue by dtxx** [harytfw/GlitterDrag#35]
[这种图片就不能下载](http://imgsrc.baidu.com/forum/w%3D580/sign=3a6459372a3fb80e0cd161df06d02ffb/1869b53eb13533fab906c628a3d3fd1f40345bb0.jpg)
[我的设置文件](https://github.com/harytfw/GlitterDrag/files/1349680/GlitterDrag_my.zip)
应该没有设置错误吧?

**Comment by harytfw** [comment]
确实是不能下载。这是是扩展或浏览器自身的运行问题，我会想办法找出具体原因

**Comment by pmhgms** [comment]
可是我用gesturefy就可以下载

**Comment by pmhgms** [comment]
而且好像跟打开方式有关，如果直接保存链接就可以。
刚才又试了几下，又都可以下载了，好迷啊……

**Comment by dtxx** [comment]
...会不会是纯图片，不给运行扩展啊?
我是没有遇过一下子可以下载，一下子又不行的情况

**Comment by harytfw** [comment]
测试结果是页面加载太快，脚本没有按步骤运行。已修复。
