### ISSUE TITLE
firefox扩展页面无法拖拽

### ISSUE THREAD

**Issue by vobasf** [harytfw/GlitterDrag#36]
firefox扩展页面无法拖拽
例如：
https://addons.mozilla.org/zh-CN/firefox/addon/glitterdrag/

**Comment by yfdyh000** [comment]
因安全原因，Firefox禁止扩展在AMO上运行。Chrome同样，禁止在商店页面上运行。
https://bugzilla.mozilla.org/show_bug.cgi?id=1295324
