### ISSUE TITLE
網頁不能進行拖拉動作。

### ISSUE THREAD

**Issue by KOKOLALAMA** [harytfw/GlitterDrag#39]
像GOOGLE搜尋結果，火狐的套件下載網站，還有其它的，

有些字不能拉，也不知為什麼，就是出現禁止符號。

録了一下影片，可能要作者費心看了，録不太好..=.=

https://www.youtube.com/watch?v=y07zryiUn6g&feature=youtu.be

**Comment by harytfw** [comment]
关于火狐的套件下載網站：#36
关于Google: 从视频中看出你还有其它的脚本作用于Google，你可以先禁用tampermonkey，再试试是否可以拖拉
Yahoo：正常执行
moztw：看起来是正常的，只是响应有点慢

**Comment by KOKOLALAMA** [comment]
影片有几个网站是正常，只是在乱连哪些是有问题的..^^"
tampermonkey，只有安装百度下载的脚本，
刚把全部套件停用，想测是哪个套件冲突，一个一个慢慢重启，
结果GOOGLE搜寻后的文字、连结跟图片就能拖拉，还真怪..
刚发现GMAIL网页也不能拉，会有禁止符号，
可能也是安全原因？
跑去YAHOO信箱倒是正常可拖拉。

作者辛苦啦
