### ISSUE TITLE
扩展启用时已有的页面不能拖拽

### ISSUE THREAD

**Issue by yfdyh000** [harytfw/GlitterDrag#42]
仅扩展启用之后载入的页面可拖拽动作。

**Comment by harytfw** [comment]
初步检测是 onMessage 事件没有触发
https://github.com/harytfw/GlitterDrag/blob/446e185370d67673a50878a1c551b536732d4ede/content_scripts/content_script.js#L717

**Comment by FungKwongman** [comment]
我这里是有些特定页面开启之后打开的也拖曳不出新标签打开链接..包括文字搜索和图像..比如火狐扩展官网addons.mozilla.org就不行..但还貌似没发现个人常用的其他网页不行

**Comment by harytfw** [comment]
@FungKwongman 你可能需要这个 https://www.ghacks.net/2017/10/27/how-to-enable-firefox-webextensions-on-mozilla-websites/

**Comment by harytfw** [comment]
换成这样应该可以
https://github.com/harytfw/GlitterDrag/blob/master/content_scripts/content_script.js#L1024-L1025
