### ISSUE TITLE
新的动作配置选项页

### ISSUE THREAD

**Issue by harytfw** [harytfw/GlitterDrag#43]
@yfdyh000 
本人审美水平不高，觉得这样可能比较直观一点。
不知道有什么建议没有，或者说你有更好的想法。

分支：https://github.com/harytfw/GlitterDrag/tree/options-page

新选项页的链接应该是 
> moz-extension:// ****** /options/newoptions.html#
![default](https://user-images.githubusercontent.com/14118053/31313634-1bde6ad6-ac1b-11e7-9ecd-547ddb5a4f95.jpg)

**Comment by yfdyh000** [comment]
谦虚了，看上去非常棒。

细节还需打磨：
刚加载时没有配置（各项未选中），恢复默认后有。
点灰色的方向会跳转到“从外部”，动态加边框提醒“限制方向”更佳。
“引擎选择”未突出如何自定义，“引擎名称”框右侧可加个按钮（链接），及进一步与“搜索模板”整合，目前重复了。
下载目录、站内搜索等，不适用时应禁用（灰色）。
一些新元素还无tooltip。
