### ISSUE TITLE
拖曳后新标签打开的位置错误

### ISSUE THREAD

**Issue by FungKwongman** [harytfw/GlitterDrag#45]
环境: win10-64位家庭版..Fx56-32位. 
1.拖曳新标签设定为(后)在偶尔正常情况下新标签打开位置现在观测应该是上一个拖曳出来的标签的右侧.
这里出现一个问题就是比如我把父标签移动了在标签栏上的位置..这时候新标签也会建立在最后一个拖曳出来的标签右则.而不是当前标签右则.
比如我搜索词条的时候拖曳了一些结果页面出来.然后又在某个结果页面拖曳了相关的页面..这样那个子页面拖出来的标签不会跟在它的父页面右则. 感觉有些错乱.现在观测不出完整规律..
2.当有固定标签的时候..标签位置设定成(后)的时候新标签会新建在固定标签的右则第一个..而不是当前标签右则.

总的来说
我这里的使用结果就是设定位置为(后)的时候极大多数情况拖曳的新标签会出现在固定标签(不管有几个固定标签)的右则第一个..如果没固定标签则出现在第一个标签的右则..

**Comment by harytfw** [comment]
对 1：我这里并无法重现出现你描述的情况，你是不是安装了旧式扩展会影响标签的打开顺序？或者开启了这些选项
![default](https://user-images.githubusercontent.com/14118053/32377370-5d671cce-c0e2-11e7-876f-4b14bd00343f.jpg)

对 2：固定标签里面之间无法存在普通标签的。你可以试试自己移动标签页的位置看能不能移动到两个固定标签页之间。

**Comment by bianjp** [comment]
遇到问题 1，试了下开启“不调整标签页的打开顺序”后正常了。

**Comment by FungKwongman** [comment]
可能是.当时是在56-56.02的前提下.有一些旧式的扩展.但是试过把其他所有扩展关掉还是出现问题.
今天升级到57之后目前正常..如果碰到有什么问题再过来反馈吧.
也顺便说句谢谢你们开发57+的拖曳 :D
