### ISSUE TITLE
拖曳中文内容的时候，也可以使用google进行搜索

### ISSUE THREAD

**Issue by LYY** [harytfw/GlitterDrag#46]
拖曳中文默认使用百度搜索，希望可以加入google搜索

**Comment by harytfw** [comment]
请参考 https://github.com/harytfw/GlitterDrag/wiki/%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8%E6%90%9C%E7%B4%A2%E5%BC%95%E6%93%8E
