### ISSUE TITLE
[feature request]在拖动后可以选择具体动作

### ISSUE THREAD

**Issue by jhdxr** [harytfw/GlitterDrag#47]
super drag togo 有一个功能，就是当拖动超出一定距离后，可以选择具体动作，如图
![qq 20171023225047](https://user-images.githubusercontent.com/1993373/31895805-baa4a48e-b844-11e7-8363-66320788313f.png)
我自己的话一般在以下两个情况下会使用这个功能：
1. 有时候会需要用到没有配置的动作的情况（例如对于链接，我配置的是所有方向都是后台标签页打开。但在少数情况下我需要前台打开，可以直接拖上去选动作。而不用单独分配一个方向给它，毕竟这种情况不到10%）
2. 拖动到最下面的那一块上可以取消

不知道现在是否还能实现这种功能了_(:з」∠)_

**Comment by harytfw** [comment]
我有两个想法，不知道你更喜欢哪一种：
1. 设置一个类似九宫格的动作面板，动作可以自己设定。比如第一行的三个命令用于文本，第二行的三个命令用于链接。可能会比较复杂。
   
2. 提供固定的命令(动作)，类似如图所示的方法。

不过还有一个问题，我没有找到 super drag togo 这个扩展,可否提供一个链接供我安装。

**Comment by jhdxr** [comment]
我目前装的是应该死就是AMO上的：[超级拖拽 0.15.1-signed.1-signed](https://addons.mozilla.org/zh-CN/firefox/addon/super-drag/)

在firefox 56b12 上（启用e10s）上目前还能正常使用


然后关于你提的两种，在保证功能都有的前提下，我肯定会喜欢第一种。我觉得火狐的大部分用户都会喜欢能够自定义的那种。配置复杂一点我觉得可以接受。因为这个配置一次就够了，而且现在配置本身也都可以同步，哪怕换了设备也不需要重新配置了。

其实我认为可以这样：针对每一种类型（文本、图片、连接），最多配置三个动作。然后一行正好三个。然后对于拖拽的内容，识别出它可能是什么类型，就把对应的那些操作显示出来。在此基础上，最后一行再放一些类型无关的动作（例如取消）。不知这么解释是否清楚。如果有需要的话我可以再去画个图说明下。

多谢

**Comment by harytfw** [comment]
抱歉拖了那么长时间
我设计的界面是这样子的![default](https://user-images.githubusercontent.com/14118053/36073199-6b1c1044-0f67-11e8-94ef-2f430bf63ff3.png)

你可以在[链接](https://addons.mozilla.org/zh-CN/firefox/addon/glitterdrag/versions/beta)里下载v1.54.0b1版本
然后在选项页里把方向的动作改为“面板”，在你拖拽的时候就会出现选择面板啦。
如果要改变面板的动作，那么到如图所示的地方修改
![1](https://user-images.githubusercontent.com/14118053/36073237-22f4ca30-0f68-11e8-9d20-6b99ef9b47f4.png)

**Comment by jhdxr** [comment]
@harytfw 感谢开发，因为我现在主力还是停留在FX52，所以之前一直没回复，抱歉。

我试用了下，几点小的建议和问题：
1. 如果拖动的起始位置在很上方（例如github的logo），那么面板会无法完整展示（最上部被挡住了）
2. 对于图片配置为下载（另存为），跳出的另存为框默认填写的文件名并不是图片的名字
3. 如果选择无动作，很奇怪下面似乎会把所有动作的配置项都展示出来了。
4. 如果可以的话，默认配置可以稍微改一改？毕竟全是前台打开会有点奇怪。。。

问题2和3也许不只是面板才存在的，而是一个全局都有的。我不知是设计如此还是的确是问题，先一并提出了。再次感谢。

**Comment by harytfw** [comment]
1. 我会参考 浏览器右键菜单显示的逻辑 重写 面板显示的位置
2. 应该是有些忘记传递文件名了
3. 这部分原先是为了方便调试，之后我会多加测试并改成正常状态
4. 会修改

代码越写越多越复杂，很难做到全方面的测试，见谅。

**Comment by jhdxr** [comment]
好的，非常感谢。
