### ISSUE TITLE
could not show css rules in firefox developer tool css inspector

### ISSUE THREAD

**Issue by adrianmak** [harytfw/GlitterDrag#48]
I'm using Firefox 52.0.4 x64
Enabling this extension will have issue on the css inspector
![baidushurufa_2017-11-5_7-30-25](https://user-images.githubusercontent.com/1168716/32410484-1df2fe6c-c1fc-11e7-9eec-d21e7c1706f6.png)

If I disable the extension, showing css rules in css inspector work again
![baidushurufa_2017-11-5_7-31-0](https://user-images.githubusercontent.com/1168716/32410485-353ed5dc-c1fc-11e7-848f-614b9a9340f9.png)

ps I installed the extension on another firefox 57 beta without such an issue

**Comment by harytfw** [comment]
fix in v1.53
