### ISSUE TITLE
自定搜尋但還是百度搜尋

### ISSUE THREAD

**Issue by delphinuz** [harytfw/GlitterDrag#49]
自定是google，但拖移文字時，還是跳到百度。

**Comment by harytfw** [comment]
不知道你是否看过这个wiki：https://github.com/harytfw/GlitterDrag/wiki/%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8%E6%90%9C%E7%B4%A2%E5%BC%95%E6%93%8E

**Comment by yipsama** [comment]
这我用插件自带的google search也还是用的百度。
但如果我自己添加一个新的google search，插件就会用google去搜索

**Comment by delphinuz** [comment]
@harytfw 有看過，我是第一次安裝完，添加gogole search，再設定google search，也確定手勢那是google search，但就是使用百度。

後來使用"恢復設定"，再重新設定一次google search，就沒問題了。

應該還是有個小bug。

**Comment by delphinuz** [comment]
@harytfw 另外，有人反饋firedoge與這插件在tab bar捲動會衝突。我是沒使用這功能，但還是反饋一下。

**Comment by harytfw** [comment]
我在卡饭回帖里只看见过一个人反馈 拖拽跟firedoge发生冲突
但是我这里同时使用firedoge和拖拽是完全没有问题的。
