### ISSUE TITLE
功能需求：拖拽文本翻译

### ISSUE THREAD

**Issue by HeJiaJunPan** [harytfw/GlitterDrag#51]
选中文本，拖拽后翻译；翻译时，在当前页面弹出窗口进行翻译。
UC脚本时代，FeiRuo曾实现过这个功能，不知作者是否能够添加下。
FeiRuo的_FeiRuoMouse.js配置链接：https://github.com/feiruo/userChromeJS/blob/master/FeiRuoMouse/_FeiRuoMouse.js

**Comment by harytfw** [comment]
本来就想实现翻译功能的，不过扩展现在还有很多问题，等可以稳定使用基本没BUG时候再考虑实现。

**Comment by harytfw** [comment]
我现在准备实现这个翻译功能，不过FeiRuo写的脚本比较复杂，如果照搬的话将来的维护可能成问题。
于是准备重新开头写（~~造轮子~~），而且我发现这个界面 [iciba划词翻译](https://greasyfork.org/zh-CN/scripts/6303-iciba%E5%88%92%E8%AF%8D%E7%BF%BB%E8%AF%91]) 比较简洁好看，所以想以这个为界面的蓝图

**Comment by harytfw** [comment]
完成
