### ISSUE TITLE
希望改进图片保存机制

### ISSUE THREAD

**Issue by BrokenChip** [harytfw/GlitterDrag#52]
1、希望下载目录可以是计算机地址，而不是默认地址子目录，这样很麻烦
2、下载的图片按域名分类文件夹，这样能节省很多时间，提高效率
3、有些图片无法下载，有些图片下载后为损坏的162字节文件
辛苦了

**Comment by thelastfantasy** [comment]
不太清楚Webextension API的限制，不过每次另存为的时候都只能从默认下载目录开始选择真的挺不方便。
不过Firefox自己的图像右键菜单“另存图像为”倒是会自动选择上一次保存的目录。

**Comment by harytfw** [comment]
如果有任何反馈请reopen这个issue
