### ISSUE TITLE
 拖拽打开的链接, 请求头似乎未加referer

### ISSUE THREAD

**Issue by mmqmzk** [harytfw/GlitterDrag#53]
这样导致有一些有盗链保护的资源用拖拽打开时403.
不知道这是不是火狐提供的API的问题.

**Comment by harytfw** [comment]
WE的标签页API没有提供修改referer的功能，
或许你可以使用 [header editor](https://addons.mozilla.org/zh-CN/firefox/addon/header-editor/) 给所有域名添加一个referer
