### ISSUE TITLE
Right/Left = First？

### ISSUE THREAD

**Issue by cswhatsgit** [harytfw/GlitterDrag#56]
link和text打开位置都设为right，但是永远在first打开，left也是同样问题。first, last, new win, private win都正常。

**Comment by harytfw** [comment]
可以传个配置看一下吗？在设置页面点那个“备份”按钮，然后上传json文件

**Comment by cswhatsgit** [comment]
好滴，请查收

[GlitterDrag-2017-12-1-12-23.zip](https://github.com/harytfw/GlitterDrag/files/1522368/GlitterDrag-2017-12-1-12-23.zip)

**Comment by harytfw** [comment]
从配置上看没有任何错误，并且我这里的打开位置都是正常的。
这个BUG很奇怪，虽然可以猜测是哪几行代码出现这个问题，但是依旧不知道造成问题的原因。

**Comment by cswhatsgit** [comment]
可能是跟其他插件有冲突？我只用了Tab Mix Plus，禁用了也没有解决，过两天再重装一下试试。
