### ISSUE TITLE
在我的浏览器上好像不起作用，Firefox57

### ISSUE THREAD

**Issue by liuxu379** [harytfw/GlitterDrag#58]
已经配置了，但是无论往左还是往右都是在新标签页搜索。
[
![qq 20171214101630](https://user-images.githubusercontent.com/21291399/33972274-0b0ba8dc-e0b8-11e7-8e0f-d2e1c13e6fe3.png)
](url)

**Comment by harytfw** [comment]
之前有用户报告过类似情况，最后发现有下面三种情况会造成方向识别错误：
* 修改过系统DPI
* 设置privacy.resistFingerprinting=true
* 修改过layout.css.devPixelsPerPx
也可能是其他暂未发现的原因（可能是跟系统或浏览器的像素、分辨率处理有关）

**Comment by liuxu379** [comment]
检查了一下，后面两个都是默认值，系统DPI的话也没动过。

**Comment by liuxu379** [comment]
在同事电脑上全新安装的浏览器仍然没效果。

**Comment by liuxu379** [comment]
我刚才试了一下12.14日的测试版，已经可以了，但是仍然会在新标签页进行搜索。
