### ISSUE TITLE
good but GDPrompt  dontwork in iframe.

### ISSUE THREAD

**Issue by drmusti** [harytfw/GlitterDrag#61]
hi big coder.
good but GDPrompt  dontwork in iframe.
for test http://urlmidi.com/test
good works but if new window result option right dont work.

if new window try drag result always last adding..please fix this bug...... main window no proplem.

and at v1.53 fixed "sometimes dont working bug" :)) thanks for fix. min-max values great working thanks this feature .
at 1.53 custom css proplem fixed.

new issue: VK videos drag drop to notepad++ or to jdownloader please dont action. any different software vk videolinks please no action.

Sincerely.

**Comment by harytfw** [comment]
Thank you for your feedback.
I wiil try to fix them.

**Comment by harytfw** [comment]
Finally I make GDPrompt available in iframe.
About the new issue you mention, I found it is a common bug of extension and   [new issue](https://github.com/harytfw/GlitterDrag/issues/77)  is open
