### ISSUE TITLE
19号更新版本后用不了了

### ISSUE THREAD

**Issue by limboking** [harytfw/GlitterDrag#65]
Firefox 57.0.1 自动更新了扩展，然后拖拽不起作用，没显示任何提示
看了设置里都正常，重启浏览器，关闭再开扩展也没用

**Comment by immeman** [comment]
遇到和楼主同样的问题，今天更新扩展后拖拽没有反应了，火狐57.0.2  32bit  win7

**Comment by harytfw** [comment]
拖拽的时候鼠标指针有没有变化?
有没有试过恢复配置？

可以的话，希望你通过下面的方法协助我进行调试：
1. 按下 Ctrl+Shift+J 打开“浏览器控制台”，点击右上角的“垃圾桶”按钮清空无用输出
2. 打开扩展管理页面，先“禁用”扩展，再“启用”扩展
3. 打开 [http://example.org/](http://example.org/), 测试一下拖拽操作
4. 打开“浏览器控制台”，对控制台进行截图，或者复制控制台里所有内容，然后上传

现在的情况是：有的人反应扩展可以正常使用；有的人报告扩展无法工作。([链接](http://www.firefox.net.cn/read-76341))
我在虚拟机里用Win7没有办法重现问题。

**Comment by immeman** [comment]
拖拽图片时鼠标变成一个虚线小方块，但屏幕不提示操作信息
我尝试恢复设置后正常了，新版本一些设置内容似乎改变了，因为我之前只改动过图片拖拽下载的动作，可能是这里出了问题，谢谢作者的回复

在 2017年12月22日 下午10:08，harytfw <notifications@github.com>写道：

**Comment by limboking** [comment]
[Exception... "Component returned failure code: 0xc1f30001 (NS_ERROR_NOT_INITIALIZED) [nsIMessageSender.sendAsyncMessage]"  nsresult: "0xc1f30001 (NS_ERROR_NOT_INITIALIZED)"  location: "JS frame :: resource://gre/modules/ExtensionUtils.jsm :: sendAsyncMessage :: line 505"  data: no]  （未知）
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  ExtensionCommon.jsm:407
Error: Could not establish connection. Receiving end does not exist.  undefined
No matching message handler for the given recipient.  MessageChannel.jsm:703
moz-extension://1e86e594-f805-e849-aeb5-c18eefc390ab/background.html: chrome tabs query did not return a result while changing window focus

  Log.js:3:3828
Error: Could not establish connection. Receiving end does not exist.  undefined
Error: WebExtension context not found!  ExtensionParent.jsm:821:13
No matching message handler for the given recipient.  MessageChannel.jsm:703
Glitter Drag: Content script is injected by browser successfully  content_script.js:3
moz-extension://1e86e594-f805-e849-aeb5-c18eefc390ab/background.html: chrome tabs query did not return a result while changing window focus

  Log.js:3:3828
No matching message handler for the given recipient.  MessageChannel.jsm:703
No matching message handler for the given recipient.  MessageChannel.jsm:703
moz-extension://1e86e594-f805-e849-aeb5-c18eefc390ab/background.html: chrome tabs query did not return a result while changing window focus

  Log.js:3:3828

**Comment by limboking** [comment]
已经附上日志。
又重新安装了扩展试了一下，还是不行。
拖动时鼠标指针也没有变化。
我是Mac上的Firefox，没有安装其他类似的扩展。

**Comment by harytfw** [comment]
我试着把把一些代码改回1.52.4的版本，不知道你那边的扩展是否正常？

**Comment by limboking** [comment]
现在已经正常了，链接和文本都OK。
