### ISSUE TITLE
新版本的图片拖拽下载反应速度比老版本要慢很多

### ISSUE THREAD

**Issue by immeman** [harytfw/GlitterDrag#69]
我尝试比较了1.52.3和最新的几个版本，发现老版本的图片拖拽下载是瞬间完成的，而新版本要等好几秒才发生下载这个动作。希望以后的新版本能恢复到以前的快速状态。 win7 火狐57.0.2

**Comment by harytfw** [comment]
旧版本是把配置缓存下来，运行的时候直接使用;新版本是每次运行命令的时候重新获取配置。
可能是这两个差别影响了响应速度。
