### ISSUE TITLE
切换DEBUG 不在語言檔案中？

### ISSUE THREAD

**Issue by zhtw2013** [harytfw/GlitterDrag#70]
切换DEBUG

發現語言檔中沒有這句
英文跟繁體都沒有

繁體
切换DEBUG→切換DEBUG

話說要不要加上「模式」？
改成 「切換至 DEBUG 模式」

![image](https://user-images.githubusercontent.com/9501406/34459183-4ddda0d4-ee23-11e7-8a3c-8fbdcaf63a7b.png)

**Comment by harytfw** [comment]
@zhtw2013 谢谢你找到的问题和建议。
最新的版本中，我添加了这些文本：https://github.com/harytfw/GlitterDrag/blob/master/_locales/zh_TW/messages.json#L608-L627
如果你想进行繁体翻译的话那现在进行了
我准备在合并后发布正式版

**Comment by zhtw2013** [comment]
Done
