### ISSUE TITLE
功能需求：增加将文本拖动到表单功能

### ISSUE THREAD

**Issue by a1cporo** [harytfw/GlitterDrag#72]
类似于以前的quickdrag，选中文字后拖拽，如果拖拽的目的地是一个表单或搜索栏等，就把文字复制到那，如果拖拽的位置不是表单，就搜索文字，感觉是非常实用的功能。可是firefox升级到57后，没找到任何拖拽扩展或是脚本能够实现这个功能，希望本扩展可以实现

**Comment by harytfw** [comment]
闪耀拖拽已经具有这个功能了

**Comment by harytfw** [comment]
没有后续的话我就关闭issue了
