### ISSUE TITLE
网页显示不全

### ISSUE THREAD

**Issue by tporwx** [harytfw/GlitterDrag#73]
启用此扩展后，会造成网页的部分内容不显示。

例如 http://www.pniao.com/ 这个网站的资源下载链接均无法显示

**Comment by harytfw** [comment]
我这里显示的是下面这个样子
![default](https://user-images.githubusercontent.com/14118053/35612660-82010556-06a4-11e8-996e-f284e20b2361.jpg)
好像正常，还是说是在其他地方无法显示？有没有具体的截图呢？

**Comment by tporwx** [comment]
58已经正常显示了。
