### ISSUE TITLE
部分页面拖拽图片感觉有明显的延迟

### ISSUE THREAD

**Issue by thelastfantasy** [harytfw/GlitterDrag#80]
不管设置的打开方式是图像还是链接，是因为整个图片都被缓存了么？
可能我笔记本电脑性能比较一般，所以感觉比较明显，拖拽纯文字链接的话就完全没有任何延迟

**Comment by harytfw** [comment]
我确实是把图片缓存起来，缓存主要是为了实现 以上传的方式搜索图片。
因为我用的是电脑，拖拽图片没有延迟感觉；如果是机械键盘+小内存的笔记本，可能会有比较大的影响。

我会在未来优化这个问题。
