### ISSUE TITLE
GIF拖拽保存失败

### ISSUE THREAD

**Issue by thelastfantasy** [harytfw/GlitterDrag#81]
URL：```https://78.media.tumblr.com/b6fb5a89623ab639c6e0ea8551171301/tumblr_p5wuuxga9C1qa94kpo1_1280.gif```

![default](https://user-images.githubusercontent.com/6077584/38159145-20486444-34d5-11e8-9c93-438a6e4414eb.png)
保存模式设为图像或者链接都下载失败，Redirector扩展已禁用

**Comment by harytfw** [comment]
![default](https://user-images.githubusercontent.com/14118053/38296306-8e64ca3e-3823-11e8-9f3e-76bfb1f03069.png)
我这里测试是可以下载的

是tumblr上所有的gif都无法保存吗？那其他网站的gif可以保存吗？

**Comment by thelastfantasy** [comment]
https://www.sankakucomplex.com/2018/04/03/mahou-shoujo-ore-crosses-boundaries/ 下载成功
http://francnaoki.tumblr.com/post/172433270952 失败
http://www.dabaoku.com/gif/041/gif003.gif 下载成功

**Comment by harytfw** [comment]
好像现在已经没问题了。我什么都没做 :）
