### ISSUE TITLE
超链接Referrer问题

### ISSUE THREAD

**Issue by thelastfantasy** [harytfw/GlitterDrag#82]
Pixiv拖拽另存为，结果保存的是403页面
建议参考：https://segmentfault.com/q/1010000011300766
https://www.w3ctech.com/topic/767

**Comment by thelastfantasy** [comment]
如果是以 XMLHttpRequest header标准的话我记得是不可以添加 Referer 的，倒是Greasemonkey的 GM_XMLHttpRequest 可以添加 Referer

**Comment by harytfw** [comment]
我试了一下，确实是不行。
我在BugZilla找了一下：发现 https://bugzilla.mozilla.org/show_bug.cgi?id=1367626 里提到会去除download的header限制，当然被当做P5的话，估计要很久才能实现。
如果照你给的资料的实现改写referer的话，那又有其他工作要做：提醒用户下载开始，失败的话又要弹出提示信息,相当于小型的下载管理器，又加重了维护。
偷懒不想实现了，等mozilla修复这个bug再说吧

**Comment by thelastfantasy** [comment]
![default](https://user-images.githubusercontent.com/6077584/38402289-b48297e4-398d-11e8-9ff3-12dae77bbb53.png)
那估计得等不少时间

**Comment by thelastfantasy** [comment]
https://greasyfork.org/zh-CN/scripts/40098-twitter-image-download-mod
这里用的ArrayBuffer类型的ajax请求不知道能不能解决问题？

**Comment by harytfw** [comment]
不行，XMLHttpRequest具体的实现被改动过了的
简单的看了代码，发现tampermonkey和greasemonkey用了同样的方法实现改写referer头：
0. 监听 webRequest.onBeforeSendHeaders 
1. 给referer头加一个前缀 "prefix_"，发送xmlhttprequest请求
2. onBeforeSendHeaders事件中发现带前缀的referer头，改写真正referer的值

不过webRequest.onBeforeSendHeaders并不会在浏览器下载文件时触发，所以不行

**Comment by thelastfantasy** [comment]
那按照我上面提过的，用ArrayBuffer方式ajax请求资源，然后以blob方式保存到超链接元素中，并加上download属性，最后click()触发点击下载呢？
这样的话应该不会妨碍webRequest.onBeforeSendHeaders触发吧。

**Comment by harytfw** [comment]
58之前，ajax可以避免跨域检查，但不会自动设置referer
幸运的是，https://bugzilla.mozilla.org/show_bug.cgi?id=1295660 说在58之后提供了两个ajax可以调用 [Content_scripts#XHR_and_Fetch](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Content_scripts#XHR_and_Fetch)

我又找了一些文档，整理了一个初步的解决思路：

  使用带refere的fetch api通过force-cache的方式获取图片（不用重新获取图片资源，节省下载时间，不用做“下载完成”之类的提示），把数据发送给后台调用browser.downloads.download() 下载。

> 然后以blob方式保存到超链接元素中，并加上download属性赋予文件名，最后运行click()方法触发下载呢？

这样做完全没有问题，只不过每次都是“另存为”（会打开文件选择框），不能静默下载

> 而且因为没有调用browser.downloads.download()方法所以下载目录也不受api限制。

只要是用户自己指定的下载目录都没有限制。 download() api 的下载目录受到限制是为了防止扩展偷偷的往电脑的其他地方（非下载目录）下载恶意东西

**Comment by thelastfantasy** [comment]
嗯，我个人就是偏好使用文件选择窗口的，静默下载的话不放心。除非是Downthemall之类的下载管理器我才会放心让其接管下载。
