### ISSUE TITLE
又发现个图片拖拽的问题

### ISSUE THREAD

**Issue by thelastfantasy** [harytfw/GlitterDrag#84]
就是闪耀拖拽在图像加载成功后才能拖拽，加载过程中或者加载失败的图片是无法拖拽的
Easy DragToGo+的话在图片加载过程中或者加载失败都是可以拖拽的

**Comment by harytfw** [comment]
Easy DragToGo+是旧式扩展，权限较大，依赖于浏览器本身，不依赖页面。

闪耀拖拽是webextension，需要靠浏览器把脚本插入到页面中才能执行，扩展只能依靠有限的参数"document_start","document_end","document_idle"决定何时插入，至于具体什么时候选择插入脚本是浏览器的事情

这不应该是扩展本身的问题，其他扩展如手势扩展和vim类扩展同样也需要页面加载完成之后才能执行（他们都需要向页面注入脚本）。
如果是不需要注入脚本的扩展那可以一直工作。

**Comment by thelastfantasy** [comment]
那加载中的图片估计是没办法了，但是加载失败的图片的话应该可以解决的吧。

**Comment by harytfw** [comment]
我基本没遇到加载失败的图片,可以给个链接测试吗？

现在我用 这个[大图](http://d.5857.com/yjkw_160303/001.jpg)测试，每次使用ctrl+F5刷新，在加载的过程中打断加载（这算是加载失败吗？），然后发现还是可以拖拽的。

**Comment by thelastfantasy** [comment]
我也没专门的链接可测试，不过可以试试墙外的链接，图片加载途中关掉SS什么的

**Comment by thelastfantasy** [comment]
另外我想如果把拖拽全部做成body上的事件委托的话，是不是就可以监听正在加载或者加载失败的图片了？

**Comment by harytfw** [comment]
全都是事件委托哦
![2](https://user-images.githubusercontent.com/14118053/38356510-83c0f484-38f2-11e8-9d3e-920437013f92.jpg)

另外,文字、链接、图像这些都是浏览器原生支持拖拽的 ([mdn文档](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/draggable)),扩展只是让它们支持更多功能的拖拽而已。

**Comment by harytfw** [comment]
我对自己限制了网速，在加载图片到一半时打断加载，发现没有加载完成的图片都显示成 24*24 的透明图片，依然可以拖拽。
没有测试用例，无法重现
