### ISSUE TITLE
配合Tree Style Tab 组件有点问题，拖拽打开的页面应为当前页面的下一级页面。

### ISSUE THREAD

**Issue by a188658587** [harytfw/GlitterDrag#86]
配合Tree Style Tab 组件有点问题，拖拽打开的页面应为当前页面的下一级页面。在Tree Style Tab里看到的是平级的。不方便Tree Style Tab的收纳。

在按住CTRL 点击链接可以点出下一级。

希望可以调整下。

还有。。。闪耀拖拽，真的超级好用！！！强烈支持！！！UI再搞搞就完美了。

**Comment by harytfw** [comment]
UI不会搞的了，因为也没多少UI会展示，没必要。
