### ISSUE TITLE
1.54.3版本拖曳多个链接为后台打开后，然后关闭后台标签时，不能激活相邻右边后台标签了？

### ISSUE THREAD

**Issue by ufo1024k** [harytfw/GlitterDrag#89]
从1.54.2升级到1.54.3版本后会出现，关闭多个拖曳到后台打开的标签后，在点击一个后台标签关闭时。

总是激活当前关闭标签左边相邻的标签，不能继续激活右边后台标签，在继续进行关闭了。

这个在1.54.2的版本中还是继续激活右边后台的标签，这样很方便，希望能改到和1.54.2一样啊

万分感谢

**Comment by harytfw** [comment]
你有没有开启 "在关闭所有子标签页后，切换到父标签页. (会覆盖上面的选项) "的选项呢?

**Comment by harytfw** [comment]
可能跟修复 #86 有关系
在启用"在关闭所有子标签页后，切换到父标签页."选项的情况下,
修复前:
![gif2](https://user-images.githubusercontent.com/14118053/39396865-c27fb1fe-4b28-11e8-9f21-cc225ae21e99.gif)

修复后:
![gif](https://user-images.githubusercontent.com/14118053/39396866-c77c31f0-4b28-11e8-8f03-798bc4488bdd.gif)

如果是上面gif所示的情况,那么我可以确定问题所在.
如果不是,欢迎继续研究讨论

**Comment by ufo1024k** [comment]
@harytfw 
是的。
1.54.2是第一张GIF的情况，

1.54.3是第二张的GIF的情况

**Comment by ufo1024k** [comment]
@harytfw 谢谢大大
这个扩展在我升级到1.54.3的时候，拖曳链接到后台标签，依次从右边起不能激活关闭标签的问题出现后，就下载此扩展想解决，但是不知道怎么设置还是不行。60测试版和59的正式版两个都试过不行。现在目前用1.54.2一切正常，先不升级了，

**Comment by ufo1024k** [comment]
@harytfw 今天用firefox61.0b3版本，安装闪耀拖曳1.54.4，以上的问题没有出现，一切正常。
发现只有在firefox59版和60版本使用1.54.3和1.54.4会出现上述问题

**Comment by harytfw** [comment]
不过我没改这部分的代码啊

我在about:config找了一下，发现是 `browser.tabs.selectOwnerOnClose` 控制了关闭标签页后的选取行为，
=true 是选取父标签页
=false 是自动选取下一个标签页
而且这个选项默认是true

那么这个问题就很容易解决： 把`browser.tabs.selectOwnerOnClose`设置为false，就会自动选取下一个标签页了。

**Comment by ufo1024k** [comment]
还是这个问题，1.55.5版本在61正式版本里正常，在62.0b3测试版里又不正常了

**Comment by ufo1024k** [comment]
@harytfw 还是这个问题，1.55.5版本在61正式版本里正常，在62.0b3测试版里又不正常了

**Comment by harytfw** [comment]
在使用 “关闭当前页后选取”扩展的过程中，发现处理的不是很好，而且我也只需要非常简单的功能。所以我把那两个选项的功能拿出来，重新做了一个扩展: https://addons.mozilla.org/zh-CN/firefox/addon/adjust-tab-selection/
应该可以解决你的需求了

使用前你应该取消这两个选项
![default](https://user-images.githubusercontent.com/14118053/43674966-473d2584-980e-11e8-97df-446e45aa72dd.jpg)

**Comment by ufo1024k** [comment]
谢谢大佬辛苦的解决问题，现在62 Beta版本下按照你给的扩展和设置办法已经解决了，真的很感谢。
