### ISSUE TITLE
新版Referer还是有问题啊

### ISSUE THREAD

**Issue by thelastfantasy** [harytfw/GlitterDrag#90]
新版好像只设置了下载图片添加Referer，然而链接还是没有加Referer

Pixiv任意页面可测试：
```
(function (){
  var a = document.createElement('a');
  a.href = `https://i.pximg.net/img-original/img/2017/11/24/12/10/10/66020503_p0.jpg`;
  a.innerText = `Pixiv链接拖拽测试`;
  a.style = `display:inline-block;position:fixed;top:50px;left:50px;font-size:24px;`
  document.body.appendChild(a);
})();
```

**Comment by harytfw** [comment]
链接肯定是加不了的。你应该使用 Header Editor 实现这种功能

**Comment by thelastfantasy** [comment]
是因为用了downloads API所以加不了么？
我对WebExtension API不了解所以不清楚到底限制在哪，不过下载的途径那么多也未必非得走downloads API吧，至少目前的还远远不能称得上完善的downloads API的话实用价值并不太大吧。

**Comment by harytfw** [comment]
不是downloads API的问题
主要是mozilla把修改Referrer头的功能放在了WebRequest中
我只是想做一个单纯的拖拽扩展，不想太多涉及这些与网络修改有关的东西（可能用户对使用WebRequest权限也有疑虑）

实现肯定没问题，但是用其他扩展也能实现功能，而且也做的更好，为什么重复造轮子呢？

**Comment by harytfw** [comment]
例如 [Smart Referer ](https://addons.mozilla.org/zh-CN/firefox/addon/smart-referer/) 就可以解决你的问题

**Comment by thelastfantasy** [comment]
站在开发者角度确实是应该避免重复造轮子吧，
但是站在客户角度的话那肯定是希望能够享受到最完善齐全的服务。
比如我说的PageExpand，设置好的话其实就足够解决Referer的问题了，但我还是希望闪耀拖拽的每个功能能够独自做到完美。

**Comment by thelastfantasy** [comment]
刚试了PageExpand的修改Referer功能，居然不能工作的，
应该是闪耀拖拽使用了downloads.download()来下载链接，但是PageExpand拦截不到downloads.download()内部请求。

**Comment by harytfw** [comment]
在 #82 你说过Referrer的问题，但是没有链接
我也不知道具体要对谁测试，所以给个链接好方便测试
可能不一定需要修改Referrer

**Comment by thelastfantasy** [comment]
就上面这个脚本就行啊，在任意pixiv页面打开控制台粘贴执行就行了

**Comment by thelastfantasy** [comment]
![default](https://user-images.githubusercontent.com/6077584/39560892-5f7df066-4ed4-11e8-973d-8b311bd8a750.png)

![default](https://user-images.githubusercontent.com/6077584/39560890-5891c7be-4ed4-11e8-8232-486f46158cb8.png)

**Comment by harytfw** [comment]
我一直以为你是在说想在新标签无法打开图片，原来你一直都在说无法下载，那我在继续看看问题出现在哪里

**Comment by harytfw** [comment]
你是在直接在这个页面拖拽下载的吧。
![default](https://user-images.githubusercontent.com/14118053/39561426-1581f42c-4ed8-11e8-96ee-ee23307ab7ac.jpg)

其实你只要点一下那张图片，直接对弹出来的大图片拖拽另存为，就可以下载了。#82 修复的就是这种情况

**Comment by thelastfantasy** [comment]
是的，不过这是浏览器内部机制，浏览器在右键另存为的时候会自动设置referer为当前页面地址，
但是闪耀拖拽使用的downloads.download()总是使用空referer，所以就有问题了。

**Comment by harytfw** [comment]
不是右键另存为
![gif](https://user-images.githubusercontent.com/14118053/39561639-7b7dcafc-4ed9-11e8-9e36-8b7815b16cad.gif)

**Comment by thelastfantasy** [comment]
那问题应该算是解决了啊，只要把同样的方法运用到超链接下载上就行了。

**Comment by harytfw** [comment]
超链接 不会实现这种下载方法
因为根据你的情况，只是在pixiv中有这种需求，而不适用于其他的的网站。

如果你想要快捷的下载pixiv的图片的话，应该考虑用脚本实现：添加一个 a标签，设置download属性，设置链接为图片的链接

**Comment by thelastfantasy** [comment]
虽然我举的例子是pixiv的，但类似的网站应该不少吧
比如图站图站反盗链啥的，有的图站设置空referer也能获取图片资源，
但有的则是严格设置referer必须同源才行

**Comment by harytfw** [comment]
启用
> 总是把含图片的链接当成图片类型

就可以把pixiv里的那个链接识别为图片了。

单纯的A标签我还是不会用 #82 fetch 的方式处理
等待 https://bugzilla.mozilla.org/show_bug.cgi?id=1367626 实现，我会尽量第一时间更新
