### ISSUE TITLE
要不要提供两种下载逻辑？

### ISSUE THREAD

**Issue by thelastfantasy** [harytfw/GlitterDrag#91]
1. WebExtension下载管理器API，也就是现在使用的下载逻辑，优点是可以静默下载，缺点是每次下载同类型文件默认目录都是固定的，还有headers受XMLHttpRequest所限制。
2. 比较Hacking一点的方式，Blob方式 + A元素download属性 + click()模拟点击下载，优点是和浏览器原生另存为一样可以使用上次保存的目录，缺点是无法静默下载，而且从部分url中解析出文件名并赋值给download属性可能会有点麻烦。

**Comment by harytfw** [comment]
不会实现
你如果想在pixiv一键下载的话，可以写一个脚本实现这种功能
