### ISSUE TITLE
in iframe or frames  #GDPrompt dont show later once drag... only once show in iframe or frames..

### ISSUE THREAD

**Issue by drmusti** [harytfw/GlitterDrag#92]
hi dear coder.
in iframe or frames  #GDPrompt dont show later once drag... 
only once show in iframe or frames..

test:
http://urlmidi.com/test
please 3-4 times drag test. 
i using OS:Win7 x64    FF:x64   v59x
please fix that bug.
Sincerely.

**Comment by harytfw** [comment]
Yes,The #GDPrompt disappear after the second time drag
I will try to figure out the solution
