### ISSUE TITLE
choose search engine from Firefox one-click search engines setting like Easy DragToGo+

### ISSUE THREAD

**Issue by derdershat** [harytfw/GlitterDrag#93]
I uses Easy DragToGo+ a lot and I am very happy that you made GlitterDrag, thank you very much.

I find it as normal user hard to add a search engine code as search template.
wouldn`t it be much easier to add the Firefox one-click search engines to your built-in dropdown menu?

in Easy DragToGo+ I used this much. Added with addon "add-to-search-bar" the search box of a site to the one-click list and in Easy DragToGo+ it was there.  I googled and they are stored in search.json.mozlz4 file.

**Comment by harytfw** [comment]
I know it is hard to let a normal user choose a right option from the complex options page.

A good news is that mozilla is implementing [Add an API to list installed search engines](https://bugzilla.mozilla.org/show_bug.cgi?id=1352598)
But when will mozilla finish is a question. You know mozilla is slow in these unimportant things.
I will keep watching the progress of this API.

Easy DragToGo+ is legacy extension so it is able to use some privilege API to retrieve the search engine.

And parsing mozlz4 file is out out the function of glitterdrag.

**Comment by tiansh** [comment]
`search.search()` currently require user action which is not useful for this extension.
See Also: [bug 1477248](https://bugzilla.mozilla.org/show_bug.cgi?id=1477248)

**Comment by harytfw** [comment]
DONE
