### ISSUE TITLE
1.54.3和1.54.4版本在Firefox 56失效

### ISSUE THREAD

**Issue by freezewind** [harytfw/GlitterDrag#94]
1.54.2更新后发现问题。
拖曳链接后不能打开链接。
已尝试全新profile。
Firefox 56.0.1 64bit
Win10

**Comment by aglent** [comment]
确认

**Comment by harytfw** [comment]
我找到原因了
首先 #86 报告说 Tree Style Tab 的网页层级有问题，所以我根据 [tabs.TAB 文档](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/Tab) 补上了openerTabId属性
不过 openerTabId属性 是57版本引入的，所以修复#86后扩展无法在ff56上正常工作
#89 也受到这个的影响

修复的方法也很简单，就是做一个版本检测
