### ISSUE TITLE
按住Ctrl拖拽BUG

### ISSUE THREAD

**Issue by CyshallChan** [harytfw/GlitterDrag#95]
如下图，按住Ctrl拖拽会打开两个标签页。
![bug](https://user-images.githubusercontent.com/22564041/40668689-bf98bcec-6397-11e8-8c56-2684af3974cb.gif)
设置如下:
![1](https://user-images.githubusercontent.com/22564041/40668695-c4c05a0e-6397-11e8-94b7-de8d3a9f6892.png)
![2](https://user-images.githubusercontent.com/22564041/40668698-c5a25986-6397-11e8-8d0f-a737232c82c1.png)

**Comment by CyshallChan** [comment]
已解决，禁用浏览器自带插件的推拽功能就可以了。如下图：
![default](https://user-images.githubusercontent.com/22564041/40717646-bcb2628c-643f-11e8-912a-3601f7311a1e.png)

**Comment by harytfw** [comment]
没问题的话我关issue
