### ISSUE TITLE
关于拖拽保存链接的问题。

### ISSUE THREAD

**Issue by smsihe** [harytfw/GlitterDrag#99]
用拖拽保存的链接，文件名中的空格会被替换成20%，直接右键链接另存为则是正常的空格。
具体的例子，yande.re左下角的“Download larger version”。。。

谢谢。:)

**Comment by harytfw** [comment]
现在应该是修复了的。

**Comment by smsihe** [comment]
> 
> 
> 现在应该是修复了的。

是的，感谢！（好像很早以前就修复了）
